services:
  db:
    image: mysql:8
    container_name: restaurant_management_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_management
    ports:
      - "3307:3306"
    volumes:
      - restaurant_management_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  restaurant_management_data:
